package memsize_test

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/tarantool/go-iproto"

	"github.com/tarantool/go-xlog/format"
	"github.com/tarantool/go-xlog/memsize"
	"github.com/tarantool/go-xlog/reader"
)

const (
	oracleIndexExtentSize = uint64(16 << 10)
	oracleTolerance       = 0.03
	oraclePercentScale    = 100
)

type liveOracle struct {
	Scenario  string            `json:"scenario"`
	ArenaUsed uint64            `json:"arena_used"`
	QuotaUsed uint64            `json:"quota_used"`
	Spaces    []liveOracleSpace `json:"spaces"`
	SlabStats []liveSlabStat    `json:"slab_stats"`
}

type liveOracleSpace struct {
	ID                 uint32            `json:"id"`
	Name               string            `json:"name"`
	TupleCount         uint64            `json:"tuple_count"`
	PayloadBytes       uint64            `json:"payload_bytes"`
	TupleHeaderBytes   uint64            `json:"tuple_header_bytes"`
	TupleFieldMapBytes uint64            `json:"tuple_field_map_bytes"`
	TupleWasteBytes    uint64            `json:"tuple_waste_bytes"`
	Indexes            []liveOracleIndex `json:"indexes"`
}

type liveOracleIndex struct {
	ID      uint32 `json:"id"`
	Name    string `json:"name"`
	Entries uint64 `json:"entries"`
	Bytes   uint64 `json:"bytes"`
}

type liveSlabStat struct {
	ItemSize  uint64 `json:"item_size"`
	ItemCount uint64 `json:"item_count"`
	MemUsed   uint64 `json:"mem_used"`
}

func TestAnalyzeLiveOracle(t *testing.T) {
	t.Parallel()

	datadir := os.Getenv("MEMSIZE_ORACLE_DIR")
	if datadir == "" {
		t.Skip("set MEMSIZE_ORACLE_DIR to a directory generated by testdata/oracle.lua")
	}

	oracleBytes, err := os.ReadFile(filepath.Join(datadir, "oracle.json"))
	require.NoError(t, err)

	var oracle liveOracle
	require.NoError(t, json.Unmarshal(oracleBytes, &oracle))

	report, err := memsize.Analyze(context.Background(), datadir, memsize.Config{
		MemtxMemory: 512 << 20,
	})
	require.NoError(t, err)

	t.Logf("%s arena: oracle=%d model=%d delta=%+.2f%%",
		oracle.Scenario, oracle.ArenaUsed, report.Total, percentDelta(report.Total, oracle.ArenaUsed))

	switch {
	case isMultikeyOracle(oracle.Scenario):
		accounted := oracle.ArenaUsed
		if isReplayOracle(oracle.Scenario) {
			accounted = oracleAccountedBytes(oracle)
		}

		assert.LessOrEqual(t, report.Total, accounted,
			"%s omits the dynamic multikey tuple field-map extent", oracle.Scenario)
	case isReplayOracle(oracle.Scenario):
		accounted := oracleAccountedBytes(oracle)
		t.Logf("%s live tuples+indexes: oracle=%d model=%d delta=%+.2f%%",
			oracle.Scenario, accounted, report.Total, percentDelta(report.Total, accounted))
		assert.InDelta(t, accounted, report.Total, float64(accounted)*oracleTolerance,
			"%s modeled tuple and index bytes", oracle.Scenario)
	default:
		assert.InDelta(t, oracle.ArenaUsed, report.Total, float64(oracle.ArenaUsed)*oracleTolerance,
			"%s arena bytes", oracle.Scenario)
	}

	assert.Equal(t, oracle.QuotaUsed, report.Total+report.Reserve, "%s quota bytes", oracle.Scenario)
	require.Len(t, report.Spaces, len(oracle.Spaces))

	for _, oracleSpace := range oracle.Spaces {
		space := findSpaceReport(t, report, oracleSpace.ID)
		assert.Equal(t, oracleSpace.Name, space.Name)
		assert.Equal(t, oracleSpace.TupleCount, space.TupleCount,
			"%s.%s tuple count", oracle.Scenario, oracleSpace.Name)
		assert.Equal(t, oracleSpace.PayloadBytes, space.PayloadBytes,
			"%s.%s payload", oracle.Scenario, oracleSpace.Name)

		oracleTupleBytes := oracleSpaceTupleBytes(oracleSpace)
		if oracleSpace.ID >= 512 {
			t.Logf("%s.%s tuples: oracle=%d model=%d delta=%+.2f%%",
				oracle.Scenario, oracleSpace.Name, oracleTupleBytes, space.TupleBytes,
				percentDelta(space.TupleBytes, oracleTupleBytes))
		}

		if isMultikeyOracle(oracle.Scenario) && hasWarning(report,
			memsize.WarnMultikeyTupleAllocation, oracleSpace.Name, "") {
			assert.Equal(t, memsize.BoundLower, space.Bound)
			assert.LessOrEqual(t, space.TupleBytes, oracleTupleBytes,
				"%s.%s tuple allocation lower bound", oracle.Scenario, oracleSpace.Name)
		} else {
			spaceTolerance := max(float64(oracleTupleBytes)*oracleTolerance,
				float64(2*oracleIndexExtentSize))
			assert.InDelta(t, oracleTupleBytes, space.TupleBytes, spaceTolerance,
				"%s.%s tuple allocation", oracle.Scenario, oracleSpace.Name)
		}

		require.Len(t, space.Indexes, len(oracleSpace.Indexes), oracleSpace.Name)

		for _, oracleIndex := range oracleSpace.Indexes {
			index := findIndexReport(t, space, oracleIndex.ID)
			assert.Equal(t, oracleIndex.Name, index.Name)
			assert.Equal(t, oracleIndex.Entries, index.Entries,
				"%s.%s.%s index entries", oracle.Scenario, oracleSpace.Name, oracleIndex.Name)

			if isMultikeyOracle(oracle.Scenario) && oracleSpace.ID >= 512 {
				t.Logf("%s.%s.%s index: entries oracle=%d model=%d, bytes oracle=%d model=%d",
					oracle.Scenario, oracleSpace.Name, oracleIndex.Name,
					oracleIndex.Entries, index.Entries, oracleIndex.Bytes, index.Bytes)
			}

			if index.Estimated {
				t.Logf("%s.%s.%s index: oracle=%d model=%d delta=%+.2f%% (estimated)",
					oracle.Scenario, oracleSpace.Name, oracleIndex.Name, oracleIndex.Bytes, index.Bytes,
					percentDelta(index.Bytes, oracleIndex.Bytes))

				indexTolerance := max(float64(oracleIndex.Bytes)*oracleTolerance,
					float64(2*oracleIndexExtentSize))
				assert.InDelta(t, oracleIndex.Bytes, index.Bytes, indexTolerance,
					"%s.%s.%s estimated index bytes", oracle.Scenario, oracleSpace.Name, oracleIndex.Name)
			} else {
				assert.Equal(t, oracleIndex.Bytes, index.Bytes,
					"%s.%s.%s index bytes", oracle.Scenario, oracleSpace.Name, oracleIndex.Name)
			}
		}
	}

	if isReplayOracle(oracle.Scenario) {
		return
	}

	statelessStats := snapshotTupleHistogram(t, report.Source.SnapPath)

	actualStats := make(map[uint64]uint64, len(oracle.SlabStats))
	for _, stat := range oracle.SlabStats {
		assert.Equal(t, stat.ItemSize*stat.ItemCount, stat.MemUsed)
		actualStats[stat.ItemSize] += stat.ItemCount
	}

	actualStats[oracleIndexExtentSize] -= report.IndexBytes / oracleIndexExtentSize
	if actualStats[oracleIndexExtentSize] == 0 {
		delete(actualStats, oracleIndexExtentSize)
	}

	statelessCount, statelessBytes := histogramTotals(statelessStats)
	actualCount, actualBytes := histogramTotals(actualStats)
	differingClasses := histogramDifferenceCount(statelessStats, actualStats)

	t.Logf("%s tuple allocator: stateless=%d (%+.2f%%), layered=%d (%+.2f%%), live=%d; stateless differing classes=%d",
		oracle.Scenario, statelessBytes, percentDelta(statelessBytes, actualBytes),
		report.TupleBytes, percentDelta(report.TupleBytes, actualBytes), actualBytes, differingClasses)
	assert.Equal(t, statelessCount, actualCount, "%s box.slab.stats tuple count", oracle.Scenario)
	assert.GreaterOrEqual(t, actualBytes, statelessBytes,
		"%s live allocator must not use less than stateless best-fit classes", oracle.Scenario)

	if isMultikeyOracle(oracle.Scenario) {
		assert.LessOrEqual(t, report.TupleBytes, actualBytes,
			"%s layered tuple allocation excludes dynamic multikey field maps", oracle.Scenario)
	} else {
		assert.InDelta(t, actualBytes, report.TupleBytes, float64(actualBytes)*oracleTolerance,
			"%s layered tuple allocation", oracle.Scenario)
	}
}

func isReplayOracle(scenario string) bool {
	return scenario == "replay" || scenario == "multikey_replay"
}

func isMultikeyOracle(scenario string) bool {
	return scenario == "multikey" || scenario == "multikey_replay"
}

func oracleAccountedBytes(oracle liveOracle) uint64 {
	var total uint64

	for _, space := range oracle.Spaces {
		total += oracleSpaceTupleBytes(space)
		for _, index := range space.Indexes {
			total += index.Bytes
		}
	}

	return total
}

func oracleSpaceTupleBytes(space liveOracleSpace) uint64 {
	return space.PayloadBytes + space.TupleHeaderBytes + space.TupleFieldMapBytes + space.TupleWasteBytes
}

func findIndexReport(t *testing.T, space memsize.SpaceReport, id uint32) memsize.IndexReport {
	t.Helper()

	for _, index := range space.Indexes {
		if index.ID == id {
			return index
		}
	}

	require.FailNowf(t, "missing index report", "space %s index %d", space.Name, id)

	return memsize.IndexReport{}
}

func snapshotTupleHistogram(t *testing.T, path string) map[uint64]uint64 {
	t.Helper()

	schema := memsize.BuildSchema()

	scanOracleSnapshot(t, path, func(row format.XRow) {
		if row.Type != iproto.IPROTO_INSERT {
			return
		}

		body, err := format.DecodeDMLBody(row.BodyRaw)
		require.NoError(t, err)

		switch body.SpaceID {
		case spaceSchemaID:
			require.NoError(t, schema.ApplySpaceRow(row.Type, body.Tuple))
		case indexSchemaID:
			require.NoError(t, schema.ApplyIndexRow(row.Type, body.Tuple))
		}
	})

	classes := memsize.NewSizeClass(8, 1.05, 16)
	histogram := make(map[uint64]uint64)

	scanOracleSnapshot(t, path, func(row format.XRow) {
		if row.Type != iproto.IPROTO_INSERT {
			return
		}

		body, err := format.DecodeDMLBody(row.BodyRaw)
		require.NoError(t, err)

		space, ok := schema.Space(body.SpaceID)
		if !ok || !space.IsMemtxData() {
			return
		}

		allocation := memsize.TupleAllocSize(space.FieldMapSize, len(body.Tuple), classes)
		histogram[uint64(allocation)]++
	})

	return histogram
}

func scanOracleSnapshot(t *testing.T, path string, visit func(format.XRow)) {
	t.Helper()

	journal, err := reader.Open(path, reader.WithAliasBodies())
	require.NoError(t, err)

	for journal.Scan() {
		visit(journal.Row())
	}

	require.NoError(t, journal.Err())
	require.NoError(t, journal.Close())
}

func histogramTotals(histogram map[uint64]uint64) (uint64, uint64) {
	var (
		count uint64
		bytes uint64
	)

	for size, classCount := range histogram {
		count += classCount
		bytes += size * classCount
	}

	return count, bytes
}

func histogramDifferenceCount(left, right map[uint64]uint64) int {
	classes := make(map[uint64]struct{}, len(left)+len(right))
	for size := range left {
		classes[size] = struct{}{}
	}

	for size := range right {
		classes[size] = struct{}{}
	}

	differences := 0

	for size := range classes {
		if left[size] != right[size] {
			differences++
		}
	}

	return differences
}

func percentDelta(value, oracle uint64) float64 {
	if oracle == 0 {
		return 0
	}

	return (float64(value) - float64(oracle)) / float64(oracle) * oraclePercentScale
}
